/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedCalendarImport } from './routes/_authed/calendar'
import { Route as AuthedPomodoroIndexImport } from './routes/_authed/pomodoro/index'
import { Route as AuthedPomodoroSessionIdImport } from './routes/_authed/pomodoro/$sessionId'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedCalendarRoute = AuthedCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPomodoroIndexRoute = AuthedPomodoroIndexImport.update({
  id: '/pomodoro/',
  path: '/pomodoro/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPomodoroSessionIdRoute = AuthedPomodoroSessionIdImport.update({
  id: '/pomodoro/$sessionId',
  path: '/pomodoro/$sessionId',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/pomodoro/$sessionId': {
      id: '/_authed/pomodoro/$sessionId'
      path: '/pomodoro/$sessionId'
      fullPath: '/pomodoro/$sessionId'
      preLoaderRoute: typeof AuthedPomodoroSessionIdImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/pomodoro/': {
      id: '/_authed/pomodoro/'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof AuthedPomodoroIndexImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedPomodoroSessionIdRoute: typeof AuthedPomodoroSessionIdRoute
  AuthedPomodoroIndexRoute: typeof AuthedPomodoroIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedPomodoroSessionIdRoute: AuthedPomodoroSessionIdRoute,
  AuthedPomodoroIndexRoute: AuthedPomodoroIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/calendar': typeof AuthedCalendarRoute
  '/pomodoro/$sessionId': typeof AuthedPomodoroSessionIdRoute
  '/pomodoro': typeof AuthedPomodoroIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/calendar': typeof AuthedCalendarRoute
  '/pomodoro/$sessionId': typeof AuthedPomodoroSessionIdRoute
  '/pomodoro': typeof AuthedPomodoroIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/pomodoro/$sessionId': typeof AuthedPomodoroSessionIdRoute
  '/_authed/pomodoro/': typeof AuthedPomodoroIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/calendar' | '/pomodoro/$sessionId' | '/pomodoro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/calendar' | '/pomodoro/$sessionId' | '/pomodoro'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/calendar'
    | '/_authed/pomodoro/$sessionId'
    | '/_authed/pomodoro/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/calendar",
        "/_authed/pomodoro/$sessionId",
        "/_authed/pomodoro/"
      ]
    },
    "/_authed/calendar": {
      "filePath": "_authed/calendar.tsx",
      "parent": "/_authed"
    },
    "/_authed/pomodoro/$sessionId": {
      "filePath": "_authed/pomodoro/$sessionId.tsx",
      "parent": "/_authed"
    },
    "/_authed/pomodoro/": {
      "filePath": "_authed/pomodoro/index.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
